services:
  frontend-main:
    ports:
      - 80:80
      - 443:443
    build:
      target: prod
      context: .
      dockerfile: Dockerfile
    volumes:
      - log_frontend_main:/log
      - ./responses_json:/srv/cedar/cedar-template-editor/api/responses_json
    environment:
      - NODE_ENV=production
      - GRAPH_API_CLIENT_SECRET=${GRAPH_API_CLIENT_SECRET}

volumes:
  log_frontend_main:
    name: log_frontend_main
